name: Build and Test

on: [push]

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit-tests:
    runs-on: ubuntu-latest
    needs: python-formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file from secrets
        run: |
          echo "PROJECT_URL=${{ secrets.PROJECT_URL }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "AUTH_URL=${{ secrets.AUTH_URL }}" >> .env
      - name: Run tests with coverage
        run: pytest

  deploy:
      name: Deploy container
      runs-on: ubuntu-latest
      needs: [python-formatting, unit-tests]
      if: github.event_name == 'push' && contains(github.ref, 'main')
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ secrets.GH_DEPLOYER }}
                password: ${{ secrets.GH_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
                context: .
                push: true
                tags: ghcr.io/travelator/database-api:latest
